### ISSUE TITLE
error in the doc

### ISSUE THREAD

**Issue by ghost** [dogwood008/Bootstrap-Image-Gallery-rails#2]
1/ there is an error in the doc from importation inside application.js
(lake of char y at the end string)

2/ and also, there is no blueimp-gallery-carousel

3/ how to remove all these gem files please ? (i will try to use the original blueimp js files instead of this gem)

**Comment by dogwood008** [comment]
Hi @jerome2 ,
1. Thank you. I fixed it: https://github.com/dogwood008/Bootstrap-Image-Gallery-rails/pull/3
2. Please use new version 1.0.1.3.1.0. It should be fixed.
3. Please use below command and remove codes:

```
$ gem uninstall Bootstrap-Image-Gallery-rails
```

```
CSS: app/assets/stylesheets/application.css
 *= require blueimp-gallery
 *= require bootstrap-image-gallery
 *= require blueimp-gallery-indicator
 *= require blueimp-gallery-video

JS: app/assets/javascripts/application.js
//= require blueimp-gallery
//= require blueimp-gallery-fullscreen
//= require blueimp-gallery-indicator
//= require blueimp-gallery-video
//= require blueimp-gallery-youtube
//= require jquery.blueimp-gallery
//= require bootstrap-image-gallery
```

**Comment by ghost** [comment]
thanks for that. I will try it again.
An other question:
for peoples choose to use sass instead of css, what to replace "*= require...."  with ?

**Comment by dogwood008** [comment]
This may be useful: http://stackoverflow.com/questions/8887824/persisting-scss-variables-in-rails-asset-pipeline
